# stack build plan using GHC 8.6.3

resolver: nightly-2019-01-04

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-api

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# allow-newer: true

extra-deps:
# hledger-lib:
# hledger:
# hledger-ui:
# hledger-web:
# hledger-api:
# Workaround for https://github.com/commercialhaskell/stack/issues/3922:
- haskell-src-exts-1.20.3
